import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/header";
import Footer from "./components/Footer/footer";

import { Toaster } from "sonner";
import { Providers } from "./providers";
import { Open_Sans } from "next/font/google";
import { BreedProvider } from "./context/BreedContext";
import { SessionWrapper } from "./components/SessionWrapper";

export const metadata: Metadata = {
  title: "The Doggo Cody",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="flex flex-col min-h-screen">
        <BreedProvider>
          <SessionWrapper>
            <Header />
            <main className="flex-1 p-10 container bg-indigo-100 mx-auto flex flex-col items-center justify-center">
              <Providers>{children}</Providers>
            </main>
            <Footer />
          </SessionWrapper>
        </BreedProvider>

        <Toaster richColors />
      </body>
    </html>
  );
}
