import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header/header";
import Footer from "./Components/Footer/footer";
import { SessionWrapper } from "./Components/SessionWrapper";
import { Toaster } from "sonner";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "The Doggo Cody",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-full flex flex-col">
        <SessionWrapper>
          <Header />
          <main className="h-full p-10 container bg-indigo-100 mx-auto flex flex-col items-center justify-center">
            <Providers>{children}</Providers>
          </main>
          <Footer />
        </SessionWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
